### ISSUE TITLE
Hanging at end of spec run

### ISSUE THREAD

**Issue by wincent** [jarib/celerity#23] opened 2010-07-07 13:39 UTC
Trying out the 0.8.0 beta and I'm seeing my spec runs hang indefinitely whenever Celerity is involved. Here's a couple of samples:

```
$ rspec spec/acceptance/sessions_spec.rb 
.......


Finished in 13.59 seconds
7 examples, 0 failures
^C
$ rspec spec/acceptance/regressions/76968b7_spec.rb 
..


Finished in 9.27 seconds
2 examples, 0 failures
^C
```

So basically any spec just sits there after completing, until I Control-C it.

<sarcasm>I did some high-tech debugging via logging</sarcasm> and found that the rspec run just hanging in the "at_exit" handler forever, right after the call to exit(); here you can see my modified version that I added so I could see what was happening:

```
at_exit {
  begin
    run(ARGV, $stderr, $stdout) ? exit(0) : exit(1)
  rescue Exception => e
    puts e.inspect
    puts e.backtrace
    raise e
  end
}
```

The specs run, we do "exit(0)", my "rescue" catches the exception (it's a SystemExit exception), logs it, re-raises it, and absolutely nothing happens...

Cheers,
Wincent

**Comment by jarib** [comment] 2010-07-07 14:22
You're probably hitting [this](http://sourceforge.net/tracker/?func=detail&aid=2985827&group_id=47038&atid=448266). Make sure to call Browser#close and all should be good. Please close this issue if that is the case.

**Comment by wincent** [comment] 2010-07-07 14:35
Yeah, looks like it.

I'm driving Celerity through Capybara (via Culerity), so Capybara is already doing this:

```
@_browser = ::Culerity::RemoteBrowserProxy.new self.class.server, {:browser => :firefox, :log_level => :off}
at_exit do
  @_browser.exit
end
```

If I add a `@_browser.close` in there prior to the `@_browser.exit` then the hanging disappears.

There are no comments on that HtmlUnit ticket that you linked. Do you think it's a bug in HtmlUnit (ie. this will be a temporary workaround)? Or something that all consumers of HtmlUnit/Celerity will need to end up doing?

Cheers,
Wincent

**Comment by wincent** [comment] 2010-07-07 14:37
Opened a ticket over in Capybara tracker to include Jonas in the discussion:

http://github.com/jnicklas/capybara/issues/issue/99

**Comment by jarib** [comment] 2010-07-07 14:40
Yes - definitely an HtmlUnit bug IMO. I can't see any rationale for having non-daemon Java threads hanging around.

They usually write to me before doing new releases, I'll make sure to bring it up then.

(Btw, there's no Celerity::Browser#exit, so I'm not sure what Culerity's doing there. I'm guessing that's where the close() call should go, i.e. not in Capybara).

**Comment by wincent** [comment] 2010-07-07 18:41
Here is where Culerity's exit method is defined:

http://github.com/langalex/culerity/blob/master/lib/culerity/remote_object_proxy.rb

At a glance, can't say I really know what it does.

**Comment by jarib** [comment] 2010-07-08 18:54
Closing this since the problem is not in Celerity.

**Closed as completed by jarib** 2010-07-08 18:54 UTC
